- job:
    name: swiftclient-swift-functional
    parent: swift-dsvm-functional
    description: |
      Run swift's functional tests with python-swiftclient
      installed from source instead as package from PyPI.
    # Ensure that we install python-swiftclient from git and
    # do not install from pypi. This is needed since the parent
    # job sets zuul_work_dir to the swift directory and uses tox
    # for installation.
    required-projects:
      - opendev.org/openstack/python-swiftclient
    vars:
      # New tox keeps breaking things as of 2023-01
      ensure_tox_version: '<4'

- job:
    name: swiftclient-functional
    parent: swift-dsvm-functional
    description: |
      Run functional tests of python-swiftclient with
      python-swiftclient installed from source instead as package from
      PyPI.
    required-projects:
      - opendev.org/openstack/python-swiftclient
    vars:
      # Override value from parent job to use swiftclient tests
      zuul_work_dir: "{{ zuul.projects['opendev.org/openstack/python-swiftclient'].src_dir }}"
      # swift can use different tox env names
      tox_envlist: func

- job:
    name: swiftclient-tox-py311
    parent: openstack-tox-py310
    vars:
      tox_envlist: py311
      bindep_profile: test py311
      python_version: '3.11'

- project:
    templates:
      - check-requirements
      - lib-forward-testing-python3
      - openstack-python3-jobs
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    experimental:
      # on-demand pipeline used to test older (but still supported) versions of python
      jobs:
        - openstack-tox-py36
        - openstack-tox-py37
    check:
      jobs:
        - swiftclient-swift-functional
        - swiftclient-functional
        - openstack-tox-py39:
            voting: true
        - openstack-tox-py310:
            voting: true
        - swiftclient-tox-py311
    gate:
      jobs:
        - swiftclient-swift-functional
        - swiftclient-functional
        - openstack-tox-py39:
            voting: true
        - openstack-tox-py310:
            voting: true
        - swiftclient-tox-py311
    post:
      jobs:
        - openstack-tox-cover
